runtime: php74
env_variables:
  CLOUD_SQL_CONNECTION_NAME: phpinternaltest:europe-west2:phpinternaltest
  DB_USER: phptest
  DB_PASS: cerebus
  DB_NAME: test
beta_settings:
      cloud_sql_instances: phpinternaltest:europe-west2:phpinternaltest